<template>
  <div>
    <gd-select
      size="larger"
      placeholder="请选择">
      <gd-option
        :value="1"
        label="哈哈">
      </gd-option>
      <gd-option
        :value="2"
        label="呵呵">
      </gd-option>
    </gd-select>
    <gd-select
      size="large"
      placeholder="请选择">
      <gd-option
        :value="1"
        label="哈哈">
      </gd-option>
      <gd-option
        :value="2"
        label="呵呵">
      </gd-option>
    </gd-select>
    <gd-select
      placeholder="请选择">
      <gd-option
        :value="1"
        label="哈哈">
      </gd-option>
      <gd-option
        :value="2"
        label="呵呵">
      </gd-option>
    </gd-select>
    <gd-select
      size="small"
      placeholder="请选择">
      <gd-option
        :value="1"
        label="哈哈">
      </gd-option>
      <gd-option
        :value="2"
        label="呵呵">
      </gd-option>
    </gd-select>

  </div>
</template>
