<template>
  <div>
    <h2>Small</h2>
    <gd-steps
      :active="2"
      type="parallel"
      size="small">
      <gd-step
        title="第一步"
        desc="这是一段相关的描述">
      </gd-step>
      <gd-step
        title="第二步"
        desc="这是一段相关的描述">
      </gd-step>
      <gd-step
        title="第三步"
        desc="这是一段相关的描述">
      </gd-step>
      <gd-step
        title="第四步"
        desc="这是一段相关的描述">
      </gd-step>
    </gd-steps>

    <h2>Large</h2>
    <gd-steps
      :active="3"
      type="parallel"
      size="large">
      <gd-step
        title="第一步"
        desc="这是一段相关的描述">
      </gd-step>
      <gd-step
        title="第二步"
        desc="这是一段相关的描述">
      </gd-step>
      <gd-step
        title="第三步"
        desc="这是一段相关的描述">
      </gd-step>
      <gd-step
        title="第四步"
        desc="这是一段相关的描述">
      </gd-step>
    </gd-steps>

    <h2>Larger</h2>
    <gd-steps
      :active="4"
      type="parallel"
      size="larger">
      <gd-step
        title="第一步"
        desc="这是一段相关的描述">
      </gd-step>
      <gd-step
        title="第二步"
        desc="这是一段相关的描述">
      </gd-step>
      <gd-step
        title="第三步"
        desc="这是一段相关的描述">
      </gd-step>
      <gd-step
        title="第四步"
        desc="这是一段相关的描述">
      </gd-step>
    </gd-steps>
  </div>
</template>
